const router = require('express').Router();
const { getClients, getClient, createClient, updateClient, deleteClient, pauseClient, resumeClient, reorderClients } = require('../controllers/client.controller');
const { protect } = require('../middleware/auth.middleware');
router.use(protect);
router.get('/', getClients);
router.post('/', createClient);
router.put('/reorder', reorderClients);
router.get('/:id', getClient);
router.put('/:id', updateClient);
router.post('/:id/pause', pauseClient);
router.post('/:id/resume', resumeClient);
router.delete('/:id', deleteClient);
module.exports = router;