const router = require('express').Router();
const { getSalaries, getMonthlySummary, createSalaryPayment, updateSalaryPayment, revertSalaryPayment } = require('../controllers/salary.controller');
const { protect } = require('../middleware/auth.middleware');
router.use(protect);
router.get('/', getSalaries);
router.get('/summary/:month/:year', getMonthlySummary);
router.post('/', createSalaryPayment);
router.put('/:id', updateSalaryPayment);
router.put('/:id/revert', revertSalaryPayment);
module.exports = router;